/* tslint:disable */
/* eslint-disable */
/**
 * Select Shop Map API
 * API for the Select Shop Map application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewShop,
  Shop,
} from '../models/index';
import {
    NewShopFromJSON,
    NewShopToJSON,
    ShopFromJSON,
    ShopToJSON,
} from '../models/index';

export interface CreateShopRequest {
    newShop: NewShop;
}

/**
 * 
 */
export class ShopsApi extends runtime.BaseAPI {

    /**
     * Creates a new shop entry
     * Create a new shop
     */
    async createShopRaw(requestParameters: CreateShopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['newShop'] == null) {
            throw new runtime.RequiredError(
                'newShop',
                'Required parameter "newShop" was null or undefined when calling createShop().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shops`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewShopToJSON(requestParameters['newShop']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new shop entry
     * Create a new shop
     */
    async createShop(requestParameters: CreateShopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createShopRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a list of all available shops
     * Get all shops
     */
    async getShopsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Shop>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/shops`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShopFromJSON));
    }

    /**
     * Returns a list of all available shops
     * Get all shops
     */
    async getShops(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Shop>> {
        const response = await this.getShopsRaw(initOverrides);
        return await response.value();
    }

}
