/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostShopInformationRequest,
} from '../models/index';
import {
    PostShopInformationRequestFromJSON,
    PostShopInformationRequestToJSON,
} from '../models/index';

export interface PostShopInformationOperationRequest {
    postShopInformationRequest?: PostShopInformationRequest;
}

/**
 * 
 */
export class ShopApi extends runtime.BaseAPI {

    /**
     * 店舗情報保存
     */
    async postShopInformationRaw(requestParameters: PostShopInformationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/shop-information`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostShopInformationRequestToJSON(requestParameters['postShopInformationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 店舗情報保存
     */
    async postShopInformation(requestParameters: PostShopInformationOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postShopInformationRaw(requestParameters, initOverrides);
    }

}
