/* tslint:disable */
/* eslint-disable */
/**
 * Select Shop Map API
 * API for the Select Shop Map application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShopLocation } from './ShopLocation';
import {
    ShopLocationFromJSON,
    ShopLocationFromJSONTyped,
    ShopLocationToJSON,
    ShopLocationToJSONTyped,
} from './ShopLocation';

/**
 * 
 * @export
 * @interface NewShop
 */
export interface NewShop {
    /**
     * Name of the shop
     * @type {string}
     * @memberof NewShop
     */
    name: string;
    /**
     * Description of the shop
     * @type {string}
     * @memberof NewShop
     */
    description?: string;
    /**
     * 
     * @type {ShopLocation}
     * @memberof NewShop
     */
    location?: ShopLocation;
}

/**
 * Check if a given object implements the NewShop interface.
 */
export function instanceOfNewShop(value: object): value is NewShop {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewShopFromJSON(json: any): NewShop {
    return NewShopFromJSONTyped(json, false);
}

export function NewShopFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewShop {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : ShopLocationFromJSON(json['location']),
    };
}

export function NewShopToJSON(json: any): NewShop {
    return NewShopToJSONTyped(json, false);
}

export function NewShopToJSONTyped(value?: NewShop | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': ShopLocationToJSON(value['location']),
    };
}

