/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddStoreInformation } from './AddStoreInformation';
import {
    AddStoreInformationFromJSON,
    AddStoreInformationFromJSONTyped,
    AddStoreInformationToJSON,
    AddStoreInformationToJSONTyped,
} from './AddStoreInformation';

/**
 * 
 * @export
 * @interface PostShopInformationRequest
 */
export interface PostShopInformationRequest {
    /**
     * 
     * @type {AddStoreInformation}
     * @memberof PostShopInformationRequest
     */
    data?: AddStoreInformation;
}

/**
 * Check if a given object implements the PostShopInformationRequest interface.
 */
export function instanceOfPostShopInformationRequest(value: object): value is PostShopInformationRequest {
    return true;
}

export function PostShopInformationRequestFromJSON(json: any): PostShopInformationRequest {
    return PostShopInformationRequestFromJSONTyped(json, false);
}

export function PostShopInformationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostShopInformationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AddStoreInformationFromJSON(json['data']),
    };
}

export function PostShopInformationRequestToJSON(json: any): PostShopInformationRequest {
    return PostShopInformationRequestToJSONTyped(json, false);
}

export function PostShopInformationRequestToJSONTyped(value?: PostShopInformationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AddStoreInformationToJSON(value['data']),
    };
}

