/* tslint:disable */
/* eslint-disable */
/**
 * Select Shop Map API
 * API for the Select Shop Map application
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShopLocation
 */
export interface ShopLocation {
    /**
     * Latitude coordinate
     * @type {number}
     * @memberof ShopLocation
     */
    lat: number;
    /**
     * Longitude coordinate
     * @type {number}
     * @memberof ShopLocation
     */
    lng: number;
}

/**
 * Check if a given object implements the ShopLocation interface.
 */
export function instanceOfShopLocation(value: object): value is ShopLocation {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    return true;
}

export function ShopLocationFromJSON(json: any): ShopLocation {
    return ShopLocationFromJSONTyped(json, false);
}

export function ShopLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lng': json['lng'],
    };
}

export function ShopLocationToJSON(json: any): ShopLocation {
    return ShopLocationToJSONTyped(json, false);
}

export function ShopLocationToJSONTyped(value?: ShopLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lng': value['lng'],
    };
}

